import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";
import NavigationMenu from "@/components/NavigationMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "its-knowledge-base",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-16 items-center px-4 border-b">
          <NavigationMenu />
          <div className="ml-auto flex items-center">Login</div>
        </div>

        {children}
      </body>
    </html>
  );
}
