import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import NavigationMenu from "@/components/NavigationMenu";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "its-knowledge-base",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div className="flex h-16 items-center px-4 border-b">
            <NavigationMenu />
            <Link
            href="/authentication"
            className={cn(
              buttonVariants({ variant: "ghost" }),
              "ml-auto flex items-center",
            )}
          >
            Login
          </Link>
          </div>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
